# Generated by Django 6.0 on 2025-12-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideevent',
            name='description',
            field=models.CharField(choices=[('Status changed to en-route', 'Status En Route'), ('Status changed to pickup', 'Status Pickup'), ('Status changed to dropoff', 'Status Dropoff')], db_index=True, max_length=50),
        ),
    ]
