# Generated by Django 6.0 on 2025-12-20 21:39

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_rideevent_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='dropoff_latitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='ride',
            name='dropoff_longitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_latitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_longitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddConstraint(
            model_name='ride',
            constraint=models.CheckConstraint(condition=models.Q(('pickup_latitude__gte', -90), ('pickup_latitude__lte', 90)), name='ride_pickup_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='ride',
            constraint=models.CheckConstraint(condition=models.Q(('pickup_longitude__gte', -180), ('pickup_longitude__lte', 180)), name='ride_pickup_longitude_range'),
        ),
        migrations.AddConstraint(
            model_name='ride',
            constraint=models.CheckConstraint(condition=models.Q(('dropoff_latitude__gte', -90), ('dropoff_latitude__lte', 90)), name='ride_dropoff_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='ride',
            constraint=models.CheckConstraint(condition=models.Q(('dropoff_longitude__gte', -180), ('dropoff_longitude__lte', 180)), name='ride_dropoff_longitude_range'),
        ),
    ]
