# Generated by Django 6.0 on 2025-12-23 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_ride_dropoff_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={'ordering': ['id_ride']},
        ),
    ]
